Repository AltCamp/altcampv1-frontend, pull requests merged in 2023-06, with the labels that each got.

#166 feat: sorted bookmark list to display in reverse
  src/pages/dashboard/components/sidebar/sidebar.module.css
  src/pages/dashboard/pages/bookmarks/bookmarks.jsx
Labels: bug

#169 feat: add password pattern guide
  src/pages/auth/register/register.jsx
  src/pages/auth/register/register.module.css
  src/pages/auth/userLogin/login/userLogin.module.css
  src/pages/dashboard/pages/account/changeprofilepicture/picturechange.jsx
  src/pages/dashboard/pages/account/hooks/useMediaHandler.js
  src/pages/dashboard/pages/account/myprojects/uploadproject/uploadproject.jsx
  src/pages/dashboard/pages/feed/createpost/createpost.jsx
Labels: bug, enhancement

#170 feat: populate bookmark input with contents
  src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx
  src/pages/dashboard/pages/feed/postcard/postcard.jsx
  src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx
  src/pages/dashboard/pages/feed/postpage/postpage.jsx
Labels: enhancement

#171 feat: added link bookmark title
  src/assets/icons/warning.png
  src/pages/dashboard/components/deletebookmarkmodal/deletebookmarkmodal.jsx
  src/pages/dashboard/components/deletebookmarkmodal/deletebookmarkmodal.module.css
  src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx
  src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkcard.module.css
  src/pages/dashboard/pages/bookmarks/bookmarks.jsx
  src/pages/dashboard/pages/bookmarks/bookmarks.module.css
  src/pages/dashboard/pages/community/questioncard/questioncard.jsx
  src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx
Labels: bug, enhancement

#175 feat: see more for post page
  src/app/slices/apiSlices/feedSlice.js
  src/pages/dashboard/pages/community/community.jsx
  src/pages/dashboard/pages/feed/feed.jsx
  src/pages/dashboard/pages/feed/feed.module.css
Labels: enhancement

#177 bug: display posts on page load + pagination
  src/pages/dashboard/pages/feed/feed.jsx
Labels: bug

#181 feat: scroll-in-to-view, enterKey and misc.
  src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx
  src/pages/dashboard/pages/community/community.jsx
  src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx
  src/pages/dashboard/pages/community/questionpage/answercard/answercard.module.css
  src/pages/dashboard/pages/community/questionpage/questionpage.jsx
  src/pages/dashboard/pages/community/questionpage/questionpage.module.css
  src/pages/dashboard/pages/feed/createpost/createpost.jsx
  src/pages/dashboard/pages/feed/feed.jsx
  src/pages/dashboard/pages/feed/postcard/postcard.jsx
  src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx
  src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.module.css
  src/pages/dashboard/pages/feed/postpage/postpage.jsx
  src/pages/dashboard/pages/feed/postpage/postpage.module.css
Labels: enhancement

#183 feat: pagination for bookmark
  src/app/slices/apiSlices/bookmarkSlice.js
  src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx
  src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkcard.module.css
  src/pages/dashboard/pages/bookmarks/bookmarks.jsx
  src/pages/dashboard/pages/bookmarks/bookmarks.module.css
Labels: enhancement

#185 feat: testing user email verification
  src/app/slices/apiSlices/accountSlices/accountMutationSlice.js
  src/app/slices/apiSlices/communitySlice.js
  src/main.jsx
  src/pages/auth/auth.jsx
  src/pages/auth/index.jsx
  src/pages/auth/register/register.jsx
  src/pages/auth/register/verifyemail/verifyemail.jsx
  src/pages/auth/register/verifyemail/verifyemail.module.css
  src/pages/dashboard/components/sidebar/sidebar.jsx
  src/pages/dashboard/pages/community/questioncard/questioncard.jsx
Labels: enhancement

#186 bug: remove programmatic navigation to dashboard
  src/pages/auth/register/register.jsx
Labels: bug

#187 bug: short circuit error mopups
  src/components/Toaster/Toaster.module.css
  src/pages/auth/register/register.jsx
  src/pages/auth/userLogin/login/userLogin.jsx
  src/pages/dashboard/components/sidebar/sidebar.jsx
  src/pages/dashboard/pages/community/askquestionpage/askquestionpage.jsx
  src/pages/dashboard/pages/community/questioncard/questioncard.jsx
  src/pages/dashboard/pages/community/questionpage/questionpage.jsx
  src/pages/dashboard/pages/feed/postcard/postcard.jsx
Labels: bug

#199 docs: env, contribution guide, & unused pkg -rm
  .gitignore
  CONTRIBUTING.md
  example.env
  package-lock.json
  package.json
  src/app/url.js
  src/pages/dashboard/pages/community/richeditor/richeditor.jsx
  src/pages/dashboard/pages/notifications/notifications.jsx
Labels: documentation
